### ISSUE TITLE
Crash - Registry Object not present

### ISSUE THREAD

**Issue by Blugori** [FaeCraft/Flamingo#4]
Hi, I ran into an issue while creating a modpack when I tried adding this mod.

Minecraft version : 1.16.1
Forge : 32.0.108
Flamingo : 1.0.1

Minecraft crashed and said : 

The game crashed whilst initializing game
Error: java.lang.NullPointerException: Registry Object not present: flamingo_ooo:flamingo_spawn_egg
Exit Code: -1

Crash log : 
[crash-2020-09-20_22.42.29-client.txt](https://github.com/FaeCraft/Flamingo/files/5252570/crash-2020-09-20_22.42.29-client.txt)

**Comment by Blugori** [comment]
the crash log.

**Comment by gdude2002** [comment]
This particular crash tends to be caused by other mods failing to load before our one. We've come across it a bunch, as it turns out - could you upload your `latest.log` from when this happened?

**Comment by Blugori** [comment]
wow I didnt expect an answer that fast xD I just encountered the same issue with your gentle fawn mod, can I give you the latest log for gentle fawn instead ? or would it be messy

**Comment by gdude2002** [comment]
Either is just fine!

**Comment by Blugori** [comment]
[latest.log](https://github.com/FaeCraft/Flamingo/files/5252608/latest.log)

here it is !

**Comment by Blugori** [comment]
I just added 20 mods at once so it might be hard to find the problem, I can try to put them one after an other

**Comment by gdude2002** [comment]
This appears to be an issue within a mod called Mapper Base. Feel free to drop them a message - here's the relevant stack trace.

```java
[20sept.2020 22:50:52.252] [Render thread/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Caught exception during event RegistryEvent.Register<minecraft:block> dispatch for modid mapperbase
java.lang.NoSuchFieldError: IRON
	at tv.mapper.mapperbase.block.BaseBlocks.lambda$static$0(BaseBlocks.java:22) ~[?:?]
	at tv.mapper.mapperbase.block.BaseBlocks$$Lambda$3865/647666196.get(Unknown Source) ~[?:?]
	at net.minecraftforge.registries.DeferredRegister.lambda$register$0(DeferredRegister.java:124) ~[?:?]
	at net.minecraftforge.registries.DeferredRegister$$Lambda$2942/858846125.get(Unknown Source) ~[?:?]
	at net.minecraftforge.registries.DeferredRegister.addEntries(DeferredRegister.java:200) ~[?:?]
	at net.minecraftforge.registries.DeferredRegister.access$000(DeferredRegister.java:61) ~[?:?]
	at net.minecraftforge.registries.DeferredRegister$EventDispatcher.handleEvent(DeferredRegister.java:172) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler_3_EventDispatcher_handleEvent_Register.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:110) [?:32.0]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$2905/895259838.accept(Unknown Source) [?:32.0]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$ErroringConsumer.accept(FMLModContainer.java:190) [?:32.0]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:113) [?:?]
	at net.minecraftforge.fml.ModList.lambda$dispatchSynchronousEvent$5(ModList.java:126) [?:?]
	at net.minecraftforge.fml.ModList$$Lambda$6038/1234654510.accept(Unknown Source) [?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) [?:1.8.0_51]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) [?:1.8.0_51]
	at net.minecraftforge.fml.ModList.dispatchSynchronousEvent(ModList.java:126) [?:?]
	at net.minecraftforge.fml.ModList.lambda$static$1(ModList.java:96) [?:?]
	at net.minecraftforge.fml.ModList$$Lambda$2871/1223360538.dispatchEvent(Unknown Source) [?:?]
	at net.minecraftforge.fml.LifecycleEventProvider.dispatch(LifecycleEventProvider.java:71) [?:?]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:214) [?:?]
	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$25(ModLoader.java:206) [?:?]
	at net.minecraftforge.fml.ModLoader$$Lambda$6092/2142052682.accept(Unknown Source) [?:?]
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:870) [?:?]
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:206) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$2(ClientModLoader.java:93) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2755/1283364748.run(Unknown Source) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:109) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2756/894332932.run(Unknown Source) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:93) [?:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:425) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:149) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.1-32.0.108.jar:32.0]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$433/442465916.call(Unknown Source) [forge-1.16.1-32.0.108.jar:32.0]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-6.1.1.jar:?]
[20sept.2020 22:50:52.261] [Render thread/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: An error occurred while dispatching event LOAD_REGISTRIES to mapperbase
[20sept.2020 22:50:52.261] [Render thread/FATAL] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: EventBus 33 shutting down - future events will not be posted.
java.lang.Exception: stacktrace
	at net.minecraftforge.eventbus.EventBus.shutdown(EventBus.java:317) [eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.afterEvent(FMLModContainer.java:123) [?:32.0]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$2906/158995547.accept(Unknown Source) [?:32.0]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$ErroringConsumer.accept(FMLModContainer.java:190) [?:32.0]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:113) [?:?]
	at net.minecraftforge.fml.ModList.lambda$dispatchSynchronousEvent$5(ModList.java:126) [?:?]
	at net.minecraftforge.fml.ModList$$Lambda$6038/1234654510.accept(Unknown Source) [?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) [?:1.8.0_51]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) [?:1.8.0_51]
	at net.minecraftforge.fml.ModList.dispatchSynchronousEvent(ModList.java:126) [?:?]
	at net.minecraftforge.fml.ModList.lambda$static$1(ModList.java:96) [?:?]
	at net.minecraftforge.fml.ModList$$Lambda$2871/1223360538.dispatchEvent(Unknown Source) [?:?]
	at net.minecraftforge.fml.LifecycleEventProvider.dispatch(LifecycleEventProvider.java:71) [?:?]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:214) [?:?]
	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$25(ModLoader.java:206) [?:?]
	at net.minecraftforge.fml.ModLoader$$Lambda$6092/2142052682.accept(Unknown Source) [?:?]
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:870) [?:?]
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:206) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$2(ClientModLoader.java:93) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2755/1283364748.run(Unknown Source) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:109) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2756/894332932.run(Unknown Source) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:93) [?:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:425) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:149) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.1-32.0.108.jar:32.0]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$433/442465916.call(Unknown Source) [forge-1.16.1-32.0.108.jar:32.0]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-6.1.1.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-6.1.1.jar:?]
```

**Comment by Blugori** [comment]
oh, thanks a lot ! (I llove your mods btw :3)

**Comment by gdude2002** [comment]
No problem, I hope it helps! And, thanks!

---

For people running across this issue in future: `Registry Object not present` errors are often caused by mods failing to load earlier on in the mod loading process. Before reporting this problem as an issue, please take a moment to read over your logs (starting from the top) and look for other errors.

Unfortunately, Forge is well known for eating useful errors when it comes to crash logs. It's just the way things are.
